---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Emerald.City
  description: Off to see the wizard.
  navLinks:
  - title: GitHub
    path: https://github.com/jfredett
  - title: Dashy Docs
    path: https://dashy.to/docs

# Optional app settings and configuration
appConfig:
  theme: colorful
  statusCheck: false
  # Every 5m
  statusCheckInterval: 300
  websearch:
    searchEngine: duckduckgo
    openingMethod: sametab
  # Config is static and located in this file
  preventWriteToDisk: true
  preventLocalSave: true
  disableConfiguration: true


# Main content - An array of sections, each containing an array of items
sections:
- name: Metrics and Monitoring
  icon: fas fa-chart-line
  items:
    - title: Grafana
      url: http://grafana.emerald.city
      icon: favicon
      target: sametab
      statusCheck: true
    - title: Prometheus
      url: http://prometheus.emerald.city
      icon: favicon
      target: sametab
      statusCheck: true

- name: Media
  icon: fas fa-tv
  items:
  - title: Jellyfin
    icon: http://jellyfin.emerald.city/web/f5bbb798cb2c65908633.png
    url: http://jellyfin.emerald.city
    target: sametab
    statusCheck: true
  - title: Disney+
    url: https://www.disneyplus.com/
    icon: favicon
    target: sametab
    statusCheck: true
  - title: Peacock
    url: https://www.peacocktv.com/
    icon: favicon
    target: sametab
    statusCheck: true
  - title: Youtube
    url: https://www.youtube.com/
    icon: favicon
    target: sametab
    statusCheck: true
  - title: Dropout
    url: https://www.dropout.tv/
    icon: favicon
    target: sametab
    statusCheck: true

- name: Fileshare
  items:
    # should only show for me
    - title: Torrents
      url: http://torrent.emerald.city
      icon: fas fa-cloud-download-alt
      target: newtab
      statusCheck: true
    - title: Radarr
      url: http://radarr.emerald.city
      icon: fas fa-film
      target: newtab
      statusCheck: true
    - title: Sonarr
      url: http://sonarr.emerald.city
      icon: fas fa-tv
      target: newtab
      statusCheck: true
    - title: Lidarr
      url: http://lidarr.emerald.city
      icon: fas fa-music
      target: newtab
      statusCheck: true
    - title: Prowlarr
      url: http://prowlarr.emerald.city
      icon: fas fa-search
      target: newtab
      statusCheck: true
    - title: Readarr
      url: http://readarr.emerald.city
      icon: fas fa-book
      target: newtab
      statusCheck: true
- name: Widgets
  widgets: 
    - type: clock
      title: Time
      icon: far fa-clock
      # TODO: Missing API key
      #    - type: weather
      #      title: Weather
      #      icon: fas fa-cloud-sun
      #      location: 01440
      #    - type: calendar
