---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: Emerald.City
  description: Off to see the wizard.
  navLinks:
  - title: GitHub
    path: https://github.com/jfredett
  - title: NixVim Options
    path: https://nix-community.github.io/nixvim/search/
  - title: NixOS Options
    path: https://search.nixos.org/options
  - title: Dashy Docs
    path: https://dashy.to/docs

# Optional app settings and configuration
appConfig:
  theme: colorful
  statusCheck: false
  # Every 5m
  statusCheckInterval: 300
  websearch:
    searchEngine: duckduckgo
    openingMethod: sametab
  # Config is static and located in this file
  preventWriteToDisk: true
  preventLocalSave: true
  disableConfiguration: true


# Main content - An array of sections, each containing an array of items
sections:
- name: Metrics and Monitoring
  icon: fas fa-chart-line
  items:
    - title: Grafana
      url: http://grafana.emerald.city
      icon: favicon
      target: sametab
      statusCheck: true
    - title: Prometheus
      url: http://prometheus.emerald.city
      icon: favicon
      target: sametab
      statusCheck: true
    - title: Unified `systemd-journal`s
      icon: fas fa-clipboard-list
      target: sametab
      url: http://grafana.emerald.city/explore?schemaVersion=1&panes=%7B%22ymt%22:%7B%22datasource%22:%22--%20Mixed%20--%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22systemd-journal%5C%22%7D%20%7C%20json%20%21%3D%20%60_SOURCE_REALTIME_TIMESTAMP%60%20%7C%20line_format%20%60%7B%7B__timestamp__%20%7C%20date%20%5C%2202%20Jan%2006%2015:04%20MST%5C%22%7D%7D%20%7C%20%7B%7BalighRight%2020%20.host%7D%7D%20%20%7C%20%7B%7BalignLeft%206%20.detected_level%7D%7D%20%7C%20%7B%7B.MESSAGE%7D%7D%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P982945308D3682D1%22%7D,%22editorMode%22:%22code%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%20%7Bjob%3D%5C%22systemd-journal%5C%22%7D%20%7C%20json%20%7C%20label_format%20timestamp%3D_SOURCE_REALTIME_TIMESTAMP%20%7C%20timestamp%20%21%3D%20%60%60%20%7C%20line_format%20%60%7B%7B.timestamp%20%7C%20unixToTime%20%7C%20date%20%5C%2202%20Jan%2006%2015:04%20MST%5C%22%20%7D%7D%20%7C%20%7B%7BalignRight%2020%20.host%7D%7D%20%7C%20%7B%7BalignLeft%208%20.detected_level%7D%7D%20%7C%20%7B%7B.MESSAGE%7D%7D%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P982945308D3682D1%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1

- name: Media
  icon: fas fa-tv
  items:
  - title: Jellyfin
    icon: http://jellyfin.emerald.city/web/f5bbb798cb2c65908633.png
    url: http://jellyfin.emerald.city
    target: sametab
    statusCheck: true
  - title: Disney+
    url: https://www.disneyplus.com/
    icon: favicon
    target: sametab
  - title: Peacock
    url: https://www.peacocktv.com/
    icon: favicon
    target: sametab
  - title: Youtube
    url: https://www.youtube.com/
    icon: favicon
    target: sametab
  - title: Dropout
    url: https://www.dropout.tv/
    icon: favicon
    target: sametab

- name: Music
  items:
    - title: Reverb
      url: https://reverb.com/
      icon: favicon
      target: sametab
    - title: Modular Grid
      url: https://modulargrid.net/e/modules/home
      icon: favicon
      target: sametab

- name: Comms and Social Media
  items:
    - title: Reddit
      url: https://old.reddit.com/
      icon: favicon
      target: sametab
    - title: Lobsters
      url: https://lobste.rs
      icon: favicon
      target: sametab
    - title: Hachyderm.io
      url: https://hachyderm.io/
      icon: favicon
      target: sametab
    - title: Instagram
      url: https://www.instagram.com/
      icon: favicon
      target: sametab
    - title: Bluesky
      url: https://bsky.app/profile/jfredett.bsky.social
      icon: favicon
      target: sametab
    - title: Gmail
      url: https://mail.google.com/
      icon: favicon
      target: sametab

- name: Tools
  items:
      - title: strftime calculator
        url: https://strftime.net/
        icon: favicon
        target: sametab
      - title: CIDR calculator
        url: https://www.ipaddressguide.com/cidr
        icon: favicon
        target: sametab
      - title: Regex101
        url: https://regex101.com/
        icon: favicon
        target: sametab
      - title: crontab.guru
        url: https://crontab.guru/
        icon: favicon
        target: sametab
      - title: Rust Combinators
        url: https://rustcombinators.com/
        favicon: favicon
        target: sametab

- name: Games
  items:
    - title: Lichess.org
      url: https://lichess.org/
      icon: favicon
      target: sametab
    - title: Chessable
      url: https://www.chessable.com/
      icon: favicon
      target: sametab
    - title: iRacing Week Planner
      url: https://iracing-week-planner.tmo.lol/
      icon: favicon
      target: sametab
    - title: VRS
      url: https://virtualracingschool.appspot.com/#/Home
      icon: favicon
      target: sametab

- name: News/Reading
  items:
      - title: MarketWatch
        url: https://www.marketwatch.com/
        icon: favicon
        target: sametab
      - title: Ars Technica
        url: https://arstechnica.com/
        icon: favicon
        target: sametab
      - title: Quanta Magazine
        url: https://www.quantamagazine.org/
        icon: favicon
        target: sametab

- name: Files
  defaultOpen: false
  items:
    # should only show for me
    - title: Torrents
      url: http://torrent.emerald.city
      icon: fas fa-cloud-download-alt
      target: sametab
      statusCheck: true
    - title: Radarr
      url: http://radarr.emerald.city
      icon: fas fa-film
      target: sametab
      statusCheck: true
    - title: Sonarr
      url: http://sonarr.emerald.city
      icon: fas fa-tv
      target: sametab
      statusCheck: true
    - title: Lidarr
      url: http://lidarr.emerald.city
      icon: fas fa-music
      target: sametab
      statusCheck: true
    - title: Prowlarr
      url: http://prowlarr.emerald.city
      icon: fas fa-search
      target: sametab
      statusCheck: true
    - title: Readarr
      url: http://readarr.emerald.city
      icon: fas fa-book
      target: sametab
      statusCheck: true
    - title: Nancy NAS
      url: http://nancy.canon:5000/#/signin
      icon: fas fa-hdd
      target: sametab
      statusCheck: true

- name: Organization
  items:
    - title: Grocy
      url: http://grocy.emerald.city
      icon: fas fa-utensils
      target: sametab
      statusCheck: true
    - title: YNAB
      url: https://app.youneedabudget.com/
      icon: favicon
      target: sametab
    - title: Bank of America
      url: https://www.bankofamerica.com/
      icon: favicon
      target: sametab
    - title: TraderSync
      url: https://app.tradersync.com/dashboard
      icon: favicon
      target: sametab

- name: Lab
  items:
      - title: SSD Prices
        url: https://diskprices.com/?locale=us&condition=new&capacity=4-&disk_types=internal_ssd
        icon: favicon
        target: sametab
      - title: 3.5" Spinner Prices
        url: https://diskprices.com/?locale=us&condition=new&capacity=12-&disk_types=internal_hdd,internal_sshd,internal_sas
        icon: favicon
        target: sametab
      - title: Tape Prices
        url: https://diskprices.com/?locale=us&condition=new&disk_types=lto7,lto8,lto9
        icon: favicon
        target: sametab
      - title: LabGopher
        url: https://labgopher.com/
        icon: favicon
        target: sametab

- name: Widgets
  widgets:
    - type: clock
      title: Time
      icon: far fa-clock
      # TODO: Missing API key
      #    - type: weather
      #      title: Weather
      #      icon: fas fa-cloud-sun
      #      location: 01440
      #    - type: calendar
      #
    - type: public-holidays
      options:
        country: US
        region: BOS
        holidayType: all
        monthsToShow: 12
        lang: en
      #    - type: gluetun-status
      #      useProxy: true
      #      options:
      #        hostname: http://localhost:8000
      #        visibleFields: public_ip,region,country,city,location,organisation,postal_code,timezone
      #    - type: cve-vulnerabilitiest

- name: Github
  widgets:
    - type: github-profile-stats
      options:
        username: jfredett
        hideLanguagesCard: true
        repos:
          - jfredett/minas-tarwon
          - jfredett/brocard
          - jfredett/hazel
