#!/usr/bin/env bash

# TODO: Extract as much of this as possible to a generic script.
# TODO: Provide that script via flake.
# TODO: Move nvmes over to BTG, no disks in DOP
# TODO: Remove all the disko stuff, do zfs by hand.
# TODO: Filesystem definitions, generated by this script?

step() {
  message=$1; shift
  echo -n "${message} ... "
  $@
  echo "done."
}


if zpool list storage; then
    step "Destroying existing Pool" {
      zpool destroy storage 
    }
fi

echo -n "Wiping disks... "
wipefs -a /dev/sda /dev/sdb /dev/sdc /dev/sdd /dev/nvme0n1 \
          /dev/sde /dev/sdf /dev/sdg /dev/sdh /dev/nvme0n2
echo "done."

# Create the raidz1 storage pool
echo -n "Creating storage pool... "
zpool create \
  storage raidz \
  -m none \
  -o ashift=12 \
  /dev/sda /dev/sdb /dev/sdc /dev/sdd
echo "done."

echo -n "Adding cache device... "
# Add the nvme0n1 device as a cache device
zpool add storage cache nvme0n1
echo "done."

echo -n "Configuring storage pool... "
zfs set compression=on storage
zfs set atime=off storage
zfs set xattr=sa storage
echo "done."


echo -n "Creating Torrent Server Dataset... "
 zfs create storage/torrent
 zfs set compression=zstd storage/torrent
 zfs set atime=off storage/torrent
 zfs set recordsize=16K storage/torrent
echo "done."


echo -n "General NFS Shared Storage Dataset... "
 zfs create storage/nfs
 zfs set compression=zstd storage/nfs
 zfs set sharenfs=on storage/nfs
 zfs set atime=off storage/nfs
 zfs set recordsize=128K storage/nfs
echo "done."

echo -n "VM Image Dataset... "
 zfs create storage/vm
 zfs set compression=zstd storage/vm
 zfs set atime=off storage/vm
echo "done."

# TODO: Move this to a separate pool? Intent is a fast SSD cache, w/ Nancy holding the larger
# library.
echo -n "Active Media Library Dataset... "
 zfs create storage/media
 zfs set compression=zle storage/media
 zfs set atime=off storage/media
 zfs set recordsize=1M storage/media
echo "done."

zpool status
zpool list storage
